version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "0:5001"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile # 👈 this is your React Dockerfile in root
    ports:
      - "0:3000"
    depends_on:
      - backend
    restart: always
